### ISSUE TITLE
Kind Request

### ISSUE THREAD

**Issue by jimjonesbr** [andreasscherbaum/pg_osm#1]
Hello Mr. Scherbaum,

I'm writing you because of your last talk on geocoding with Nominatim in the PostgreSQL EU conference in Prague - I saw it a few days ago on youtube. Some time ago I wrote a small fdw that has in principle the same goal of your plpython solution:

https://github.com/jimjonesbr/nominatim_fdw

After watching your talk I decided to take it out of our private GitLab and publish it on GitHub, and now I am looking for use cases to test it. It turned out that a fdw was kind of an overkill for our tiny little project, so I didn't have the opportunity to put the fdw under proper stress. To keep it short: could point me to use cases or data samples, so that I can properly test the fdw? Any tips would be much appreciated!

Thanks in advance!
Best regards,
Jim

**Comment by andreasscherbaum** [comment]
I'm not quite clear what the ask is here.

What I did was finding a data set which gives me reliable data (coordinates), and then run my extension on the data and compare it.

**Comment by jimjonesbr** [comment]
Thanks for the reply

> What I did was finding a data set which gives me reliable data (coordinates), and then run my extension on the data and compare it.

Sounds straightforward actually quite enough :) I was just wondering if you had a data set that I could also use to test my code, but after your message I realize that anything that has reliable coordinates is good enough for my regression tests.

Thanks!
